name: Autotimer8

on: 
  workflow_dispatch:
#  schedule:
#    - cron:  '*/2 * * * *'

jobs:
  timerpoi:
  
    runs-on: ubuntu-latest

    steps:  
    - name: set up access to azure boards 
      run: |
        echo "AZURE_DEVOPS_EXT_PAT=${{secrets.ADO_PAT}}" >> $GITHUB_ENV 
        az devops configure --defaults project=devops-openhack-code-base organization=https://dev.azure.com/restonmtc
        
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: get the staging slot on/off status
      id: vars-p-staging
      shell: bash
      run: |
        STAGINGSTATUS=$(az webapp show --name openhack22trips --resource-group openhack22rg --slot staging --query state -o tsv)
        echo "set-output name=STAGINGSTATUS::${STAGINGSTATUS}"
        echo ::set-output name=STAGINGSTATUS::${STAGINGSTATUS}
        
    - name: if the staging slot is stopped, there is nothing to do
      run: exit
      if: steps.vars-t-staging.outputs.STAGINGSTATUS == 'Stopped'
      
    - name: perform health check on staging
      id: vars-p-staging-h
      shell: bash
      run: |
        HCHECK=$(curl -o /dev/null -s -w "%{http_code}\n" https://openhack22poi-staging.azurewebsites.net/api/healthcheck/poi)
        echo "set-output name=HCHECK::${HCHECK}"
        echo ::set-output name=HCHECK::${HCHECK}
        
    - name: if we fail the health check, shut off the staging slot
      run: az webapp stop --name openhack22poi --resource-group openhack22rg --slot staging
      if: steps.vars-p-staging-h.outputs.HCHECK != '200'
      
    # check for bugs here, and shut off if any
  
    - name: get the staging slot on/off status
      id: vars-p-staging-p
      shell: bash
      run: |
        STAGINGSTATUS=$(az webapp traffic-routing show --name openhack22poi --resource-group openhack22rg --query "[?name=='staging'].reroutePercentage" -o tsv)
        echo "set-output name=STAGINGSTATUS::${STAGINGSTATUS}"
        echo ::set-output name=STAGINGSTATUS::${STAGINGSTATUS}
        
    - name: if we are at 10, go to 20
      run: az webapp traffic-routing set --distribution staging=25 --name openhack22poi --resource-group openhack22rg
      if: steps.vars-t-staging-p.outputs.STAGINGSTATUS == '10.0'
    
    - name: if we are at 25, go to 50
      run: az webapp traffic-routing set --distribution staging=50 --name openhack22poi --resource-group openhack22rg
      if: steps.vars-t-staging-p.outputs.STAGINGSTATUS == '25.0'

   # if this is 50, send a notification (this would happen a lot.....so we need to limit these)
