name: Autotimer8

on: 
  workflow_dispatch:
#  schedule:
#    - cron:  '*/2 * * * *'

jobs:
  timerpoi:
  
    runs-on: ubuntu-latest

    steps:  
    - name: set up access to azure boards 
      run: |
        echo "AZURE_DEVOPS_EXT_PAT=${{secrets.ADO_PAT}}" >> $GITHUB_ENV 
        az devops configure --defaults project=devops-openhack-code-base organization=https://dev.azure.com/restonmtc
        
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: get the staging slot on/off status
      id: vars-p-staging
      shell: bash
      run: |
        STAGINGSTATUS=$(az webapp show --name openhack22poi --resource-group openhack22rg --slot staging --query state -o tsv)
        echo "set-output name=STAGINGSTATUS::${STAGINGSTATUS}"
        echo ::set-output name=STAGINGSTATUS::${STAGINGSTATUS}
        
    - name: if the staging slot is stopped, there is nothing to do
      run: exit
      if: steps.vars-p-staging.outputs.STAGINGSTATUS == 'Stopped'
      
    - name: perform health check on staging
      id: vars-p-staging-h
      shell: bash
      run: |
        HCHECK=$(curl -o /dev/null -s -w "%{http_code}\n" https://openhack22poi-staging.azurewebsites.net/api/healthcheck/poi)
        echo "set-output name=HCHECK::${HCHECK}"
        echo ::set-output name=HCHECK::${HCHECK}
        
    - name: if we fail the health check, shut off the staging slot, send a bug to dev ops, and then exit
      run: |
        az boards work-item create --title "Staging error; Poi version $(az webapp config appsettings list --name openhack22poi --resource-group openhack22rg --slot staging --query "[?contains(name, 'DEPLOYAPPVERSION')].value" -o tsv) in staging has failed the health check.  It is being disabled" --type Bug --query id -o tsv
        az webapp stop --name openhack22poi --resource-group openhack22rg --slot staging
        exit 1
      if: steps.vars-p-staging-h.outputs.HCHECK != '200'  

    - name: check for bugs here, and shut off if any
      id: vars-nbugs
      shell: bash
      run: |
        VER=$(az webapp config appsettings list --name openhack22poi --resource-group openhack22rg --slot staging --query "[?contains(name, 'DEPLOYAPPVERSION')].value" -o tsv)
        echo "ver ${VER}"
        ITER="devops-openhack-code-base\\${VER}"
        echo "iter ${ITER}"
        NUMBUGS=$(az boards query --wiql "SELECT [System.Title] FROM workitems WHERE ([System.IterationPath] = '${ITER}')" --query [].fields[].'"System.Title"' -o tsv | wc -l)
        echo "set-output name=NUMBUGS::${NUMBUGS}"
        echo ::set-output name=NUMBUGS::${NUMBUGS} 
        
    - name: Stop if there are any bugs
      run: |
        az webapp stop --name openhack22poi --resource-group openhack22rg --slot staging
        exit 1
      if: steps.vars-nbugs.outputs.STAGINGSTATUS != '0'
  
    - name: get the staging slot on/off status
      id: vars-p-staging-p
      shell: bash
      run: |
        STAGINGSTATUS=$(az webapp traffic-routing show --name openhack22poi --resource-group openhack22rg --query "[?name=='staging'].reroutePercentage" -o tsv)
        echo "set-output name=STAGINGSTATUS::${STAGINGSTATUS}"
        echo ::set-output name=STAGINGSTATUS::${STAGINGSTATUS}
        
    - name: if we are at 10, go to 20
      run: az webapp traffic-routing set --distribution staging=25 --name openhack22poi --resource-group openhack22rg
      if: steps.vars-p-staging-p.outputs.STAGINGSTATUS == '10.0'
    
    - name: if we are at 25, go to 50
      run: |
        az webapp traffic-routing set --distribution staging=50 --name openhack22poi --resource-group openhack22rg
        exit 1
        if: steps.vars-p-staging-p.outputs.STAGINGSTATUS == '25.0'

    - name: call the logic app to send the notification
      run: |
        CTHEADER="Content-Type: application/json"
        JSONBODY='{"address": "pfisher@microsoft.com", "prurl": "https://github.com/snapfisher/devops-openhack-code-base/actions?query=workflow%3A.github%2Fworkflows%2Fmanualfinish8.ymlhttps://github.com/snapfisher/devops-openhack-code-base/actions?query=workflow%3A.github%2Fworkflows%2Fmanualfinish8.yml", "prtitle": "'
        TITLE=$(az webapp config appsettings list --name openhack22poi --resource-group openhack22rg --slot staging --query "[?contains(name, 'DEPLOYAPPVERSION')].value" -o tsv)
        JSONBODYEND='"}'
        URL='https://prod-07.eastus2.logic.azure.com:443/workflows/c07eaa8191f140e5bab0b54ab4954187/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=nTUKzeefgXx6uyt5qd7HRPtmXpa40iOzwZvwIHUD5qE'
        echo "${JSONBODY}${HTMLURL}${JSONBODYMID}${TITLE}${JSONBODYEND}"
        curl -X POST -H "${CTHEADER}" -d "${JSONBODY}${TITLE}${JSONBODYEND}" ${URL}
        if: steps.vars-p-staging-p.outputs.STAGINGSTATUS == '50.0'
     
     
     
