name: bluegreen5 CD

on:
  workflow_dispatch:
#  push:
#    branches: 'main'

jobs:
  pullpoi:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    #- run: az acr build --image "devopsoh/api-poi:changeme" --registry openhack22acr.azurecr.io --file Dockerfile .
    #  working-directory: apis/poi/web
      
    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
    - run: docker pull openhack22acr.azurecr.io/devopsoh/api-poi:changeme
    - run: docker tag openhack22acr.azurecr.io/devopsoh/api-poi:changeme openhack22acr.azurecr.io/devopsoh/api-poi:${GITHUB_RUN_ID}
    - run: docker push openhack22acr.azurecr.io/devopsoh/api-poi:${GITHUB_RUN_ID}
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack22poi'
        slot-name: 'staging'
        images: 'openhack22acr.azurecr.io/devopsoh/api-poi:${{ github.run_id }}'
        
    - name: check slot deployment
      uses: wei/curl@master
      with:
        args: https://openhack22poi-staging.azurewebsites.net/api/healthcheck/poi
        
    - run: az webapp deployment slot swap -g openhack22rg -n openhack22poi --slot staging --target-slot production
      
#  pulltrips:
#
#    runs-on: ubuntu-latest

#    steps:
#    - name: Azure Login
#      uses: Azure/login@v1.1
#      with:
#        creds: ${{secrets.AZURE_CREDENTIALS}}
          
          
#    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
#    - run: docker pull openhack22acr.azurecr.io/devopsoh/api-trips:changeme
#    - run: docker tag openhack22acr.azurecr.io/devopsoh/api-trips:changeme openhack22acr.azurecr.io/devopsoh/api-trips:${GITHUB_RUN_ID}
#    - run: docker push openhack22acr.azurecr.io/devopsoh/api-trips:${GITHUB_RUN_ID}
#    - run: az webapp deployment slot create --name openhack22trips --resource-group openhack22rg --slot newversion
    
#    - uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'openhack22trips/newversion'
#        images: 'openhack22acr.azurecr.io/devopsoh/api-trips:${{ github.run_id }}'
      
#  pulluser:

#    runs-on: ubuntu-latest

#    steps:
#    - name: Azure Login
#      uses: Azure/login@v1.1
#      with:
#        creds: ${{secrets.AZURE_CREDENTIALS}}

#    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
#    - run: docker pull openhack22acr.azurecr.io/devopsoh/api-user-java:changeme
#    - run: docker tag openhack22acr.azurecr.io/devopsoh/api-user-java:changeme openhack22acr.azurecr.io/devopsoh/api-user-java:${GITHUB_RUN_ID}
#    - run: docker push openhack22acr.azurecr.io/devopsoh/api-user-java:${GITHUB_RUN_ID}
#    - run: az webapp deployment slot create --name openhack22userjava --resource-group openhack22rg --slot newversion

#    - uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'openhack22userjava/newversion'
#        images: 'openhack22acr.azurecr.io/devopsoh/api-user-java:${{ github.run_id }}'


#  pulluserprofile:

#    runs-on: ubuntu-latest

#    steps:
#    - name: Azure Login
#      uses: Azure/login@v1.1
#      with:
#        creds: ${{secrets.AZURE_CREDENTIALS}}
        
#    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
#    - run: docker pull openhack22acr.azurecr.io/devopsoh/api-userprofile:changeme
#    - run: docker tag openhack22acr.azurecr.io/devopsoh/api-userprofile:changeme openhack22acr.azurecr.io/devopsoh/api-userprofile:${GITHUB_RUN_ID}
#    - run: docker push openhack22acr.azurecr.io/devopsoh/api-userprofile:${GITHUB_RUN_ID}
#    - run: az webapp deployment slot create --name openhack22userprofile --resource-group openhack22rg --slot newversion
      
#    - uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'openhack22userprofile/newversion'
#        images: 'openhack22acr.azurecr.io/devopsoh/api-userprofile:${{ github.run_id }}'
