name: main CD

on:
  workflow_dispatch:
  push:
    branches: 'main'

jobs:
  pullapi1:

    runs-on: ubuntu-latest

    steps:
    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
    - run: docker pull devopsoh/api-poi:changeme
