name: main CD

on:
  workflow_dispatch:
#  push:
#    branches: 'main'

jobs:
  pullpoi:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - run: az acr build --image "devopsoh/api-poi:changeme" --registry openhack22acr.azurecr.io --file Dockerfile .
      working-directory: apis/userprofile
      
    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
    - run: docker pull openhack22acr.azurecr.io/devopsoh/api-poi:changeme
    - run: docker tag openhack22acr.azurecr.io/devopsoh/api-poi:changeme openhack22acr.azurecr.io/devopsoh/api-poi:${GITHUB_RUN_NUMBER}
    - run: docker push openhack22acr.azurecr.io/devopsoh/api-poi:${GITHUB_RUN_NUMBER}
      
  pulltrips:

    runs-on: ubuntu-latest

    steps:
    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
    - run: docker pull openhack22acr.azurecr.io/devopsoh/api-trips:changeme
    - run: docker tag openhack22acr.azurecr.io/devopsoh/api-trips:changeme openhack22acr.azurecr.io/devopsoh/api-trips:${GITHUB_RUN_NUMBER}
    - run: docker push openhack22acr.azurecr.io/devopsoh/api-trips:${GITHUB_RUN_NUMBER}
      
  pulluser:

    runs-on: ubuntu-latest

    steps:
    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
    - run: docker pull openhack22acr.azurecr.io/devopsoh/api-user-java:changeme
    - run: docker tag openhack22acr.azurecr.io/devopsoh/api-user-java:changeme openhack22acr.azurecr.io/devopsoh/api-user-java:${GITHUB_RUN_NUMBER}
    - run: docker push openhack22acr.azurecr.io/devopsoh/api-user-java:${GITHUB_RUN_NUMBER}
      
  pulluserprofile:

    runs-on: ubuntu-latest

    steps:
    - run: docker login openhack22acr.azurecr.io --username ${{secrets.AZURE_SP_ID}} --password ${{secrets.AZURE_SP_PWD}}
    - run: docker pull openhack22acr.azurecr.io/devopsoh/api-userprofile:changeme
    - run: docker tag openhack22acr.azurecr.io/devopsoh/api-userprofile:changeme openhack22acr.azurecr.io/devopsoh/api-userprofile:${GITHUB_RUN_NUMBER}
    - run: docker push openhack22acr.azurecr.io/devopsoh/api-userprofile:${GITHUB_RUN_NUMBER}
